apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hormuz.fullname" . }}
  labels:
    {{- include "hormuz.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "hormuz.selectorLabels" . | nindent 6 }}
