import { CampaignLink } from '../components/CampaignLink';
import { pageMetadata } from '../../lib/metadata';
import { REPOSITORY, SOURCE_REVISION, SOURCE_VERSION, OCI_VERSION, MACOS_VERSION, sitePath, sourcePath } from '../../lib/site.mjs';
import { PageFrame, PageHero } from '../components/PageFrame';
import { CodeBlock } from '../components/CodeBlock';

export const metadata = pageMetadata('AI Work examples, setup & team downloads — Hormuz', 'Try OpenAI and Anthropic examples, connect your own gateway, and attach actual delivery evidence to AI work.', '/docs/');

const personalInstall = `git clone --branch ${SOURCE_VERSION} --depth 1 https://github.com/Xpounder-com/hormuz.git
cd hormuz
python3 -m venv .venv
source .venv/bin/activate
python -m pip install 'PyJWT[crypto]>=2.14,<3' '.[client,context]'
hormuz context resources install
hormuz personal qualify --json`;
const quickstart = `git clone --branch ${SOURCE_VERSION} --depth 1 https://github.com/Xpounder-com/hormuz.git
cd hormuz
python3 -m venv .venv
source .venv/bin/activate
python -m pip install --editable .
hormuz demo`;
const workRevision = SOURCE_REVISION === 'main' ? '<REVIEWED_40_CHARACTER_COMMIT>' : SOURCE_REVISION;
const workInstall = `python3 -m venv .venv-hormuz-ai-work
source .venv-hormuz-ai-work/bin/activate
python -m pip install 'hormuz[client,context] @ git+https://github.com/Xpounder-com/hormuz.git@${workRevision}'
hormuz work --help`;
const workExamples = `git clone https://github.com/Xpounder-com/hormuz.git
cd hormuz
git checkout --detach ${workRevision}
python3 -m venv .venv-examples
source .venv-examples/bin/activate
python -m pip install --editable .
python tools/ai_work_provider_examples.py
python tools/ai_work_provider_examples.py --list`;
const references = [
  ['Identity', 'OIDC JWT verification', 'Issuer, audience, signatures, and explicit subject mapping. Your identity tooling supplies and refreshes tokens.', 'docs/OIDC.md'],
  ['Control', 'Policy administration', 'Templates, preview, immutable versions, activation, and rollback. Privileged administration is separate from inference access.', 'docs/POLICY_CONTROL.md'],
  ['Evidence', 'Usage reporting', 'Current UTC-month reports by person, team, model, client, and provider. Captured gateway requests and estimated costs only.', 'docs/USAGE.md'],
  ['Operations', 'Deployment contract', 'Readiness, graceful drain, deadlines, and deployment-owned controls. Reference evidence is not customer certification.', 'docs/OPERATIONS.md'],
];

export default function DocsPage() {
  return <PageFrame active="docs">
    <PageHero eyebrow="Documentation" title={<>Install free.<br /><span>Make the first request count.</span></>}>
      <p>Run the AI Work examples locally, connect your own provider account, or join an existing team gateway.</p>
      <div className="hero-actions"><a className="button button-primary" href="#examples">Try the examples ↓</a><a className="button button-ghost" href="#mac">Team Mac app ↓</a></div>
    </PageHero>
    <div className="docs-shell">
      <aside className="docs-sidebar" aria-label="Documentation navigation">
        <div><strong>Get started</strong><a href="#examples">Runnable examples</a><a href="#ai-work">AI Work connection</a><a href="#personal">Personal Optimizer</a><a href="#mac">Team Mac companion</a><a href="#first-request">First governed request</a><a href="#quickstart">Provider-free demo</a><a href="#downloads">Source & OCI versions</a><CampaignLink href={sitePath('/integrations/')}>Connect a client</CampaignLink><a href="#policy-tour">Try a policy change</a></div>
        <div><strong>Go deeper</strong>{references.map(([tag, title, , path]) => <a key={tag} href={sourcePath(path)}>{title} ↗</a>)}<a href={sourcePath('SUPPORT.md')}>Support matrix ↗</a></div>
      </aside>
      <article className="docs-content">
        <section id="examples" className="docs-section"><p className="section-label">Try the current AI Work source</p><h2>Start with an example. Bring your own workload.</h2><p className="docs-lead">Run OpenAI Responses, Chat Completions, and Anthropic Messages examples through the actual gateway. The default tour uses only disposable local provider simulators and needs no API key.</p><p>Install Python 3.11+ and Git, then check out the same source revision as this page. Installation downloads Python dependencies. The tour creates temporary local state and removes it on exit.</p><CodeBlock code={workExamples} label="Provider-free AI Work example tour" />{SOURCE_REVISION === 'main' && <p>Replace <code>&lt;REVIEWED_40_CHARACTER_COMMIT&gt;</code> with the exact candidate commit in the <a href={`${REPOSITORY}/pull/456`}>AI Work pull request ↗</a>. These examples are separate from the published v1.8.0 release.</p>}<p>Explore request attribution, scoped budgets, cost/speed/outcome priorities, streaming, exact answer reuse, and corrective repeats. Read the provider guide before choosing an explicit live run: provider calls may be billed, models and configured rates need to match your account, and a local simulator cannot qualify a real provider.</p><div className="resource-actions"><a href={sourcePath('examples/providers/README.md')}>OpenAI and Anthropic live examples ↗</a><a href={sourcePath('examples/sdk/README.md')}>OpenAI and Anthropic SDK recipes ↗</a><a href={sourcePath('docs/AI_WORK_DELIVERY_EXAMPLES.md')}>Connect actual GitHub or Linear delivery ↗</a><a href={sourcePath('docs/TRY_HORMUZ.md')}>Complete first-run walkthrough ↗</a></div><p>Workflow delivery joins an explicitly bound repository event to the work record. A CI check, merged pull request, model response, or cache hit remains its stated observation; none alone proves the whole job was correct. Share a sanitized compatibility report through the GitHub template when you try your own stack.</p></section>
        <section id="ai-work" className="docs-section"><p className="section-label">AI Work source path</p><h2>Connect requests to the work they belong to.</h2><p className="docs-lead">An operator enables AI Work on the gateway and authorizes your application. Use the authenticated dashboard to create a work record, choose a budget and priority, and inspect captured attempts.</p><p>AI Work budgets currently cover text inputs with validated configured upper cost bounds. Image, audio, document, and provider-resolved inputs are rejected when that bound is unavailable.</p><p>API agents must carry the durable work ID across their requests and iterations. The SDK and CLI guide shows attachment, scoped budgets, pause and continuation, and sourced observations from actual checks. AI Work requires the reviewed source candidate on both the gateway and CLI client, followed by qualification of your agent and provider. The published v1.8.0 installers do not include these new AI Work commands. A public workspace sign-up alone does not enable them.</p><p>With Python 3.11+ and Git installed, create a separate environment for the candidate CLI:</p><CodeBlock code={workInstall} label="AI Work candidate CLI" />{SOURCE_REVISION === 'main' && <p>Replace <code>&lt;REVIEWED_40_CHARACTER_COMMIT&gt;</code> with the full reviewed commit supplied by your administrator. This local website build has no source pin.</p>}<p>This installs the candidate client package. Your administrator still configures and qualifies the gateway; it does not update the signed Mac app, provision a service, or activate paid inference.</p><div className="resource-actions"><a href={sourcePath('docs/AI_WORK_AGENT_INTEGRATION.md')}>SDK, CLI, and agent attachment guide ↗</a><a href={sourcePath('docs/AI_WORK_RUNTIME.md')}>Routing, budget, and exact reuse contract ↗</a><CampaignLink href={sitePath('/work/')}>Open the configured gateway →</CampaignLink></div></section>
        <section id="personal" className="docs-section"><p className="section-label">Personal Optimizer · $0 Hormuz fee</p><h2>Keep your coding agent. See what Hormuz improves.</h2><p className="docs-lead">The current personal release supports terminal use on Apple Silicon Macs running macOS 14 or later, with Codex CLI 0.148.0. Direct mode uses your own OpenAI API credential, stored in the OS keyring. It needs no team gateway, organization, or Hormuz account.</p><p>Install Python 3.11 or newer and the pinned Codex CLI, then install the published {SOURCE_VERSION} source and run the provider-free qualification:</p><CodeBlock code={personalInstall} label="Personal Optimizer setup" /><p>After qualification, follow the <a href={sourcePath('docs/PERSONAL_OPTIMIZER.md') + '#connect-directly'}>direct connection instructions ↗</a> to add your provider credential and launch Codex. Run <code>hormuz personal benefit --profile personal-codex</code> to see eligible and transformed traffic; <code>hormuz personal off --profile personal-codex</code> restores the ordinary request path.</p><div className="docs-callout"><span aria-hidden="true">i</span><p><strong>Cost and scope:</strong> Hormuz has no personal software fee or checkout. Your provider may bill API usage. The initial automatic transform applies only to supported repetitive <code>rg --files</code> results; byte and token estimates are not a provider bill or a guaranteed saving. The signed Mac app below is the team gateway companion, while this direct personal path runs from the terminal.</p></div></section>
        <section id="mac" className="docs-section"><p className="section-label">Join your existing team gateway</p><h2>Your connection. Your usage. On your Mac.</h2><p className="docs-lead">Hormuz {MACOS_VERSION.slice(1)} supports Apple Silicon on macOS 14 or later. The signed, notarized archive includes its context helper and tokenizer resources; no separate Python installation is needed.</p><div className="resource-actions"><a className="button button-primary" href={`${REPOSITORY}/releases/download/${MACOS_VERSION}/Hormuz-${MACOS_VERSION.slice(1)}-notarized.zip`}>Download Hormuz {MACOS_VERSION.slice(1)} for Mac ↓</a><a href={`${REPOSITORY}/releases/tag/${MACOS_VERSION}`}>Release & verification evidence ↗</a></div><ol className="numbered-list"><li>Extract the archive and move Hormuz.app to Applications.</li><li>Get your gateway URL, organization, and unique identity or invitation from your administrator. The app does not provision a hosted gateway.</li><li>Connect and sign in using the gateway’s configured identity flow. Review and save the supported client launcher.</li><li>Launch your coding client through Hormuz, choose an approved model, and make one small authorized request. Inspect your usage and connection state.</li></ol><p>Context optimization is Off by default under <strong>Client → Context optimization</strong>. It changes the next request on this device and connection. <CampaignLink href={sitePath('/demo/#compaction')}>Try exactly what it does →</CampaignLink></p><details className="disclosure"><summary>Verify the Mac archive</summary><p>Compute the downloaded archive’s SHA-256 with <code>shasum -a 256 Hormuz-{MACOS_VERSION.slice(1)}-notarized.zip</code> and compare it with <a href={`${REPOSITORY}/releases/download/${MACOS_VERSION}/SHA256SUMS.txt`}>the published checksums</a>. Keep normal Gatekeeper checks enabled. Intel Macs are unsupported. Upgrades use versioned archives; there is no automatic updater.</p></details><div className="docs-callout"><span aria-hidden="true">i</span><p><strong>No team gateway yet?</strong> Follow the source quickstart below or <CampaignLink href={sitePath('/enterprise/')}>choose help setting it up</CampaignLink>. A download alone does not create a provider account or a team connection.</p></div></section>
        <section id="quickstart" className="docs-section">
          <p className="section-label">01 / Install and run</p><h2>The complete first-run path.</h2>
          <p className="docs-lead">Use Git and Python 3.11+ on macOS or Linux. Installation downloads Python dependencies; the demo itself contacts only local loopback simulators. Do not expose the demo to the internet.</p>
          <CodeBlock code={quickstart} label="Stable source quickstart" />
          <p>On Windows, activate the virtual environment with <code>.venv\Scripts\Activate.ps1</code> in PowerShell; consult the <a href={sourcePath('SUPPORT.md')}>support matrix</a> before choosing a deployment platform.</p>
          <div className="code-window"><div className="code-window-bar"><span>Expected successful result</span><span>Synthetic requests</span></div><pre tabIndex={0}><code>{`PASS allowed request reached the loopback provider simulator
PASS unapproved model was rerouted and output-capped
PASS detected secret was redacted before provider egress
PASS denied request made no provider call
PASS content-free evidence validated: 4 usage events, 1 security event
PASS external provider calls: 0 (3 loopback simulator calls)`}</code></pre></div>
          <p>Temporary gateway state is removed on exit. Your checkout and virtual environment remain; run <code>deactivate</code> when finished. This is a product tour, not a performance benchmark, live-provider test, or independent-user study.</p>
          <div className="docs-callout"><span aria-hidden="true">i</span><p><strong>Something failed?</strong> Confirm Python 3.11+, the active virtual environment, and permission to bind local ports. Share the command, version, and sanitized error via <a href={sourcePath('SUPPORT.md')}>Support</a>—never provider tokens, prompts, or customer configuration.</p></div>
        </section>
        <section id="downloads" className="docs-section">
          <p className="section-label">02 / Select a distribution</p><h2>Core {SOURCE_VERSION.slice(1)}. Mac companion {MACOS_VERSION.slice(1)}.</h2>
          <div className="table-scroll"><table className="comparison-table release-downloads"><caption>Current published distribution boundaries</caption><thead><tr><th scope="col">Distribution</th><th scope="col">Version</th><th scope="col">Use and boundary</th></tr></thead><tbody>
            <tr><th scope="row">Source</th><td>{SOURCE_VERSION}</td><td>CLI, gateway, adapter SDK, and Aider integration on Python 3.11+. Personal Optimizer support is limited to macOS 14+ on Apple Silicon. <a href={`${REPOSITORY}/releases/download/${SOURCE_VERSION}/hormuz-${SOURCE_VERSION.slice(1)}.tar.gz`}>Source archive ↗</a> · <a href={`${REPOSITORY}/releases/tag/${SOURCE_VERSION}`}>Release evidence ↗</a></td></tr>
            <tr><th scope="row">Apple Silicon companion</th><td>{MACOS_VERSION}</td><td>Developer ID signed and notarized for Apple Silicon, macOS 14+. <a href="#mac">Install and connect →</a></td></tr>
            <tr><th scope="row">Signed OCI reference</th><td>{OCI_VERSION}</td><td>Linux AMD64 image at ghcr.io/xpounder-com/hormuz:{OCI_VERSION}. Pin the digest in <a href={`${REPOSITORY}/releases/download/${OCI_VERSION}/oci-release-summary.json`}>release evidence ↗</a> and follow <a href={sourcePath('docs/OCI.md')}>signature verification ↗</a>.</td></tr>
            <tr><th scope="row">Windows development preview</th><td>1.5.0-dev.1</td><td>Unsigned, unsupported Windows 10/11 x64 development source, not a qualified installer. Real sign-in, physical desktop and clean-install acceptance remain open. <a href={sourcePath('clients/rust/windows/README.md')}>Preview guide ↗</a> · <a href={REPOSITORY + '/issues/340'}>Open qualification ↗</a></td></tr>
          </tbody></table></div>
          <p>{SOURCE_VERSION} core artifacts pass provider-free release checks. The maintained live-provider evidence remains the v1.2.0 OpenAI-only qualification; Claude Code/Anthropic retains its protocol contract and same-candidate live qualification remains open. Use the checksums and exact release evidence for your chosen artifact.</p>
          <p><a href={`${REPOSITORY}/releases/download/${SOURCE_VERSION}/SHA256SUMS.txt`}>Download {SOURCE_VERSION} core checksums ↓</a></p>
          <p>Documentation links follow this website's reviewed source revision when it is pinned. Local builds without a pin follow main. Stable downloads retain their labeled release versions; use tagged source when reproducing a release result. No PyPI installation or package ownership is implied by this guide.</p>
        </section>
        <section id="first-request" className="docs-section"><p className="section-label">From a demo to your workflow</p><h2>Connect one client. See its first usage.</h2><ol className="numbered-list"><li>Name a gateway operator and start with a non-production client workflow. Configure server-side provider accounts, model aliases/rates, unique identities, and policy using the <a href={sourcePath('README.md') + '#configure-providers-and-clients'}>gateway configuration guide</a>.</li><li>Generate the client settings for your organization-controlled gateway URL. Keep company provider credentials on the gateway.</li><li>Use the generated launcher or configuration to run one small authorized request with an approved model. Test an agreed policy denial and confirm that it made no provider call.</li><li>Run the team/model report below. Confirm the attributed identity, current UTC month, token categories, estimated cost, and request outcome.</li></ol><CodeBlock label="Generate Codex settings · example hostname, not a running service" code={'hormuz --config hormuz.json client config codex --url https://hormuz.example.com'} /><CodeBlock label="Inspect governed usage" code={'hormuz --config hormuz.json status --group-by team\nhormuz --config hormuz.json status --group-by model --team engineering'} /><p>Use your configured team ID instead of engineering. Empty reports can mean no completed captured requests in the current month, a mismatched identity/team, or traffic taking a different route. <CampaignLink href={sitePath('/integrations/')}>Client-specific setup, limits, and verification →</CampaignLink></p></section>
        <section id="policy-tour" className="docs-section">
          <p className="section-label">03 / Change a policy</p><h2>See the administrative workflow offline.</h2>
          <CodeBlock code="hormuz policy demo" label="Offline policy tour" />
          <p>This separate, zero-network tour exercises policy templates, checks, simulation, and evidence. It cleans up by default. It does not prove a live PostgreSQL administrative deployment.</p>
          <p>Then follow the <a href={sourcePath('marketing/tutorials/policy-and-evidence.md')}>policy-and-evidence walkthrough</a> to inspect a proposed change and the <a href={sourcePath('docs/POLICY_CONTROL.md')}>governed policy guide</a> before staging or activating policies in a managed environment.</p>
        </section>
        <section className="docs-section"><p className="section-label">Reference library</p><h2>Go deeper by control surface.</h2><div className="doc-reference-grid">{references.map(([tag, title, copy, path]) => <a href={sourcePath(path)} key={tag}><span>{tag}</span><h3>{title}</h3><p>{copy}</p><strong>Open reference ↗</strong></a>)}</div></section>
        <section className="docs-next"><div><span>Next</span><h2>Connect one supported client.</h2></div><CampaignLink className="button button-primary" href={sitePath('/integrations/')}>Client walkthrough →</CampaignLink></section>
      </article>
    </div>
  </PageFrame>;
}
