import { CampaignLink } from './components/CampaignLink';
import { pageMetadata } from '../lib/metadata';
import { sitePath, sourcePath, OWNER_NAME, OWNER_URL, MACOS_VERSION } from '../lib/site.mjs';
import { SiteFooter } from './components/SiteFooter';
import { SiteHeader } from './components/SiteHeader';
import { WorkPriorities } from './components/WorkPriorities';

export const metadata = pageMetadata('Hormuz — Keep your agents. Choose your budget and pace.', 'Control supported AI traffic, understand what work consumes, and choose cost or speed priorities. Connect your existing coding agents to Hormuz.', '/');

export default function Home() {
  return <div className="landing-home ai-work-home"><SiteHeader active="platform" /><main id="content" tabIndex={-1}>
    <section className="landing-hero work-hero" id="top">
      <div className="work-hero-grid"><div className="landing-hero-copy">
        <h1>Keep your agents.<br /><em>Choose your budget and pace.</em></h1>
        <p className="landing-deck">Bring your existing coding tools through Hormuz. Set the spending boundary, see what your work consumes, and keep control as AI usage grows.</p>
        <div className="landing-actions"><CampaignLink className="button landing-primary" href={sitePath('/docs/#examples')}>Try the examples <span aria-hidden="true">→</span></CampaignLink><CampaignLink className="button landing-secondary" href={sitePath('/evidence/')}>Inspect the evidence <span aria-hidden="true">→</span></CampaignLink></div>
        <p className="landing-reassurance">Free software · Your provider accounts · Provider charges separate<br />AI Work requires qualification on your exact workflow.</p>
      </div><div className="work-passage" aria-label="The governed request path">
        <div><span>01</span><h2>Your agents</h2><p>Use a qualified client connection.</p></div><div><span>02</span><h2>Hormuz</h2><p>Identity, spending limits, and request controls before dispatch.</p></div><div><span>03</span><h2>Your providers</h2><p>Eligible requests continue; usage returns to the work record.</p></div>
      </div></div>
      <p className="hero-owner">A product of <a href={OWNER_URL}>{OWNER_NAME} ↗</a> · Led by Mehrdad Zaker</p>
    </section>
    <section className="landing-section work-journey" id="spend" aria-labelledby="work-journey-title">
      <div className="landing-heading"><h2 id="work-journey-title">A budget.<br /><em>A piece of work. A result.</em></h2><p>The AI bill belongs beside the work that consumed it. Follow the whole episode, including attempts and uncertain provider outcomes.</p></div>
      <ol className="work-steps"><li id="policy"><span>01 / SET THE BOUNDARY</span><h3>Choose the commitment.</h3><p>Apply scoped gateway budgets using configured cost estimates and approved-model policies. Reservations account for requests in flight before dispatch.</p></li><li><span>02 / RUN THE WORK</span><h3>Keep your familiar tools.</h3><p>Connect a supported agent and attribute its requests to the work. Protocol, model, and credential compatibility remain part of the route.</p></li><li><span>03 / INSPECT THE RECORD</span><h3>See what happened.</h3><p>Review captured spending estimates, attempts, elapsed time, and available outcome evidence. A response or cache hit does not automatically mean a task is complete.</p></li></ol>
      <WorkPriorities />
    </section>
    <section className="landing-section work-proof-band" id="proof"><div><h2>Run it yourself.<br /><em>Then connect your work.</em></h2><p>Try OpenAI Responses, Chat Completions, and Anthropic Messages through a disposable local gateway. Explore spending limits, priorities, and answer reuse without a provider account, then select a small live example using your own account.</p><p>Recorded runs and local examples use simulated providers. Real usage, delivery, and outcomes stay visible as separate evidence.</p><div className="resource-actions"><a className="text-link" href={sourcePath('docs/TRY_HORMUZ.md')}>Read the GitHub walkthrough ↗</a><CampaignLink className="text-link" href={sitePath('/evidence/')}>Inspect the recorded proof →</CampaignLink></div></div><CampaignLink className="button landing-primary" href={sitePath('/docs/#examples')}>Run the examples <span aria-hidden="true">→</span></CampaignLink></section>
    <section className="landing-section work-coverage" id="setup"><span id="compaction" className="anchor-target" /><div className="landing-heading"><h2>Your exact stack.<br /><em>A clear boundary.</em></h2><p>Hormuz controls requests that pass through its governed route. Closed applications and unrelated subscriptions do not become controllable by connecting GitHub.</p></div><dl className="coverage-rows"><div><dt>Current gateway paths</dt><dd>OpenAI Responses and Anthropic Messages protocol paths, plus OpenAI-compatible Chat Completions in the AI Work source path. Verify your client version, tool behavior, streaming, and model configuration before expanding usage.</dd></div><div><dt>Personal and team connections</dt><dd>The Personal Optimizer runs from the terminal on Apple Silicon Macs, with pinned Codex CLI and your own OpenAI API account. Automatic compaction covers narrowly eligible repetitive tool output. The separate Mac gateway companion is version {MACOS_VERSION.slice(1)}.</dd></div><div><dt>Cost and speed decisions</dt><dd>The AI Work runtime uses explicit priorities and eligible routes. Real-provider outcome and performance qualification remains workflow-specific.</dd></div><div><dt>Cache and completion</dt><dd>Provider prompt caching remains a model execution. Opt-in exact answer reuse is bounded by work, identity, context, model, and policy. Reuse counts stay separate from task outcomes.</dd></div></dl><div className="resource-actions"><CampaignLink className="text-link" href={sitePath('/integrations/')}>Check supported connections →</CampaignLink><CampaignLink className="text-link" href={sitePath('/security/')}>Data and credential boundaries →</CampaignLink></div></section>
    <section className="landing-section work-start" id="install"><div><h2>Connect the workflow<br /><em>you already have.</em></h2><p>Run the open-source software yourself, or discuss a Cloud workspace for your supported traffic. Confirm scope and activation before paying; subscription billing starts at checkout.</p></div><div className="work-start-actions"><CampaignLink className="button landing-primary" href={sitePath('/contact/?interest=work')}>Discuss your workflow ↗</CampaignLink><CampaignLink className="text-link" href={sitePath('/docs/')}>Install the software →</CampaignLink><CampaignLink className="text-link" href={sitePath('/work/')}>Open AI Work →</CampaignLink><CampaignLink className="text-link" href={sitePath('/plans/#cloud')}>Cloud pricing and cancellation →</CampaignLink></div></section>
  </main><SiteFooter /></div>;
}
