import { EnterprisePlans } from '../components/EnterprisePlans';
import { CampaignLink } from '../components/CampaignLink';
import { commercial, PILOT_PRICE, SUPPORT_PRICE, selfServiceSupport } from '../../lib/commercial.mjs';
import { pageMetadata } from '../../lib/metadata';
import { sitePath, sourcePath } from '../../lib/site.mjs';
import { PageFrame, PageHero } from '../components/PageFrame';

export const metadata = pageMetadata('Enterprise pricing & paid pilot — Hormuz', 'Install Hormuz free. Get self-service support for $2,000/month, or evaluate one workflow with a $15,000, 90-day paid pilot.', '/enterprise/');

const comparison = [
  ['Gateway, identity, policy, budgets, secret controls, evidence', 'Included in the Apache-2.0 core', 'The same open-source capabilities'],
  ['Installation and configuration', 'Self-service documentation and examples', 'Scoped integration and configuration assistance'],
  ['Support', 'Public, best-effort community channels', 'Self-service: one gateway, 4 hours/month, response within 2 business days. Pilot and custom support follow their agreed scope.'],
  ['Evaluation evidence', 'Reproducible demos and reference tests', 'A workflow-specific evidence pack and gap review'],
  ['Infrastructure, provider accounts, credentials, retention', 'Operated by you', 'Still operated by you unless explicitly contracted otherwise'],
  ['Managed hosting, 24/7 SLA, certification', 'Not included', 'Not an established offering or implied commitment'],
];

export default function EnterprisePage() {
  return <PageFrame active="enterprise">
    <PageHero eyebrow="Enterprise evaluation & support" title={<>Install free.<br /><span>Pay for practical help.</span></>}>
      <p>Use Hormuz’s open-source controls with your own gateway and provider accounts. Add ongoing support for your operating team, or a guided 90-day pilot to evaluate one workflow.</p>
      <div className="hero-actions"><CampaignLink className="button button-primary" href={sitePath('/docs/')}>Install free →</CampaignLink><a className="button button-ghost" href="#comparison">Compare the paths ↓</a></div>
    </PageHero>
    <EnterprisePlans />
    <section className="section" id="comparison">
      <div className="section-heading narrow"><p className="section-label">What is free. What is paid.</p><h2>The value is help making it work in your environment.</h2><p>Start independently, subscribe to the support plan below, or agree a guided pilot with the maintainer. All product controls remain open source.</p></div>
      <div className="table-scroll"><table className="comparison-table"><caption>Open-source product and paid services</caption><thead><tr><th scope="col">Area</th><th scope="col">Open source</th><th scope="col">Enterprise engagement</th></tr></thead><tbody>{comparison.map(([area, oss, paid]) => <tr key={area}><th scope="row">{area}</th><td>{oss}</td><td>{paid}</td></tr>)}</tbody></table></div>
      <p className="after-grid">Self-service support has the fixed scope and renewal terms below. Pilot and custom engagements require a separate agreement on scope, capacity, start date, and commercial terms before payment.</p>
    </section>
    <section className="enterprise-control-section"><div className="enterprise-control-inner"><div className="enterprise-control-heading"><p className="section-label light">A practical starting point</p><h2>One team. One client path. Named owners.</h2></div><div className="enterprise-control-list">
      <div><span>01</span><h3>Good initial fit</h3><p>A platform or engineering lead introducing Codex or Claude Code under company provider accounts, with a security reviewer and a named gateway operator.</p></div>
      <div><span>02</span><h3>Your prerequisites</h3><p>A non-production environment, authorized provider account, unique identities, approved test inputs, and someone empowered to decide policy and acceptance criteria.</p></div>
      <div><span>03</span><h3>Not a fit yet</h3><p>A turnkey hosted service, fleet-wide monitoring, employee productivity scoring, semantic DLP guarantees, or a certification-backed 24/7 service requirement.</p></div>
    </div></div></section>
    <section className="pilot-section section" id="pilot"><div className="pilot-heading"><p className="section-label">90-day paid pilot · $15,000 USD</p><h2>Prove one workflow before widening the route.</h2><p>Begin with a short fit and scope discussion. A shorter evaluation can be agreed before a 90-day commitment; no work or calendar slot is confirmed by an inquiry.</p></div><div className="pilot-steps">
      <article><span>Days 1–15</span><h3>Map</h3><p>Name the client, identity, provider credential, policy, secret, budget, and evidence boundaries. Agree prerequisites and pass/fail criteria.</p><strong>Control map + acceptance plan</strong></article>
      <article><span>Days 16–45</span><h3>Prove</h3><p>Run the non-production workflow. Inspect allowed and denied requests, identity attribution, policy changes, and metadata exports.</p><strong>Evidence pack + issue log</strong></article>
      <article><span>Days 46–90</span><h3>Decide</h3><p>Review usability and operating effort. Test agreed recovery boundaries and list remaining production gates, owners, and costs.</p><strong>Go / no-go memo + handoff</strong></article>
    </div><div className="docs-callout"><span aria-hidden="true">✓</span><p><strong>Acceptance is agreed, not implied:</strong> the named client works; a forbidden request makes no upstream call; policies and identity are attributable; exports contain no prompt/response bodies; operational gaps have owners. Targets for latency, scale, availability, and cost accuracy require separate evidence.</p></div>
      <div className="resource-actions"><CampaignLink className="button button-primary" href={sitePath('/downloads/hormuz-pilot-brief.pdf')}>Read the pilot brief ↓</CampaignLink><a className="text-link" href={sourcePath('marketing/PILOT.md')}>Editable scope & responsibilities ↗</a></div>
    </section>
    <section className="section prose-section" id="support"><p className="section-label">Start directly · no pilot required</p><h2>Self-service support. $2,000/month.</h2><p>For a team operating one self-hosted Hormuz gateway: up to <strong>4 support hours per billing month</strong>, with a <strong>response within 2 business days</strong>. Get policy and configuration guidance, upgrade planning, troubleshooting, and evidence review from the founder.</p><p>Your subscription renews monthly until canceled. Cancel before the next renewal; your current paid period and free software access remain available. A response is an acknowledgment and next step, not a guaranteed resolution within two days. Provider charges, hosting, 24/7 operations, and work beyond the included hours are not included.</p><div className="resource-actions">{selfServiceSupport.paymentUrl ? <a className="button button-primary" href={selfServiceSupport.paymentUrl} rel="noreferrer">Start support · $2,000/month ↗</a> : <CampaignLink className="button button-primary" href={sitePath('/contact/?interest=support')}>Get self-service support details →</CampaignLink>}<a className="text-link" href="#activate">What happens after payment? ↓</a></div><p>Checkout is operated by AI and Robotics Solutions. Your card statement may show LINKEDFULL.COM. Prices are USD; applicable taxes are additional. No proprietary software features or hosted account are required for this service.</p></section>
    <section className="section prose-section" id="activate"><p className="section-label">Your paid service, made concrete</p><h2>Paid at Stripe? Start your support here.</h2><p>This page does not verify payment. Wait for Stripe’s payment confirmation and receipt, then use the next steps below. If checkout failed or you left without paying, you can continue using Hormuz free.</p><ol className="numbered-list"><li>Email <a href="mailto:mehrdadz@neuralint.io?subject=Hormuz%20self-service%20support%20activation">mehrdadz@neuralint.io</a> from your checkout email with the receipt reference, organization, and the question or workflow you want help with. Do not send provider keys, passwords, or customer prompts.</li><li>Mehrdad verifies the payment and replies within two business days to establish the support channel and the gateway covered by your plan. Your four-hour allowance belongs to the paid billing month.</li><li>Send policy, configuration, upgrade, and troubleshooting requests through that channel. Work beyond the monthly allowance needs a separate agreement before any extra charge.</li></ol><h3 id="cancel">Manage or cancel support</h3><p>Email <a href="mailto:mehrdadz@neuralint.io?subject=Cancel%20Hormuz%20self-service%20support">mehrdadz@neuralint.io</a> from your checkout email before the next renewal and include your receipt or subscription reference. The request stops the next renewal; confirmation follows through the support channel. Billing details and cancellation are handled by the seller. The open-source product remains available after cancellation.</p><div className="resource-actions"><a className="button button-primary" href="mailto:mehrdadz@neuralint.io?subject=Hormuz%20self-service%20support%20activation">Activate my support by email ↗</a><CampaignLink className="button button-outline" href={sitePath('/docs/')}>Install the free product →</CampaignLink></div><p>A charge without a receipt or an unclear payment result is a reason to check with the seller before trying again. There is no automatic resubmission from this website.</p></section>
    {(commercial.pilotPaymentUrl || commercial.supportPaymentUrl) && <section className="section offer-section" id="payment"><p className="section-label">For custom support and pilot agreements</p><h2>Ready to start your agreed scope?</h2><p>Use these links only after Hormuz has confirmed your scope and start date. Check the amount and billing terms at Stripe before paying. Payment alone does not qualify a deployment or expand your support agreement.</p><div className="resource-actions">
      {commercial.pilotPaymentUrl && <a className="button button-primary" href={commercial.pilotPaymentUrl} rel="noreferrer"><span>Pay pilot fee · {PILOT_PRICE} USD</span><span aria-hidden="true">↗</span></a>}
      {commercial.supportPaymentUrl && <a className="button button-outline" href={commercial.supportPaymentUrl} rel="noreferrer"><span>Custom agreed support · {SUPPORT_PRICE} USD/month</span><span aria-hidden="true">↗</span></a>}
    </div><p>Checkout is operated by AI and Robotics Solutions. Your card statement may show LINKEDFULL.COM. Support renews monthly until canceled under your agreed cancellation terms. Provider charges and infrastructure are separate.</p></section>}
    <section className="enterprise-truth section"><div><span className="status-ring" aria-hidden="true"><i /></span><strong>v1.2.0 · preserved v1 contracts</strong></div><h2>Engineering evidence is not enterprise certification.</h2><p>Reference checks do not establish your TLS, credential custody, retention, recovery, high availability, compliance, or independent security review. No customer endorsements, certifications, invoice reconciliation, or production SLA are claimed.</p><CampaignLink href={sitePath('/security/')}>Review the security boundary →</CampaignLink></section>
    <section className="page-cta"><div><p className="section-label light">Founder-led · Mehrdad Zaker</p><h2>Bring one workflow and its constraints.</h2><p>Install independently, or discuss the scope of a guided pilot before payment.</p></div><CampaignLink className="button button-light" href={sitePath('/contact/?interest=pilot')}>Discuss my pilot →</CampaignLink></section>
  </PageFrame>;
}
