import { pageMetadata } from '../../lib/metadata';
import { REPOSITORY, sitePath, sourcePath } from '../../lib/site.mjs';
import { PageFrame, PageHero } from '../components/PageFrame';

export const metadata = pageMetadata('Project & buyer resources — Hormuz', 'Download the Hormuz overview, pilot brief, trust packet, and buyer deck. Explore tutorials and ways to contribute.', '/resources/');

const downloads = [
  ['Overview', 'The buyer one-pager', 'The problem, open-source boundary, evaluation fit, and next step.', '/downloads/hormuz-overview.pdf'],
  ['Pilot', 'A bounded evaluation plan', 'Proposed 90-day scope, responsibilities, acceptance criteria, and terms to agree.', '/downloads/hormuz-pilot-brief.pdf'],
  ['Trust', 'Data flow & security brief', 'Transient content, retained metadata, credentials, operator duties, and review questions.', '/downloads/hormuz-trust-brief.pdf'],
  ['Presentation', 'The short buyer deck', 'A seven-slide editable briefing for an engineering or security evaluation.', '/downloads/hormuz-buyer-briefing.pptx'],
];

export default function ResourcesPage() {
  return <PageFrame active="resources"><PageHero eyebrow="Project resources" title={<>Enough context.<br /><span>A concrete next step.</span></>}><p>Source-linked materials for trying Hormuz, evaluating a supported pilot, or explaining the project to your team. No account or email gate.</p></PageHero><section className="section"><div className="section-heading narrow"><p className="section-label">For an evaluation</p><h2>Take the brief, not a sales promise.</h2><p>These materials describe the current open core and a proposed services engagement. They do not establish a separate enterprise edition, delivery commitment, SLA, or certification.</p></div><div className="doc-reference-grid">{downloads.map(([tag, title, copy, href]) => <a key={title} href={sitePath(href)}><span>{tag}</span><h3>{title}</h3><p>{copy}</p><strong>Download {href.endsWith('.pptx') ? 'PPTX' : 'PDF'} ↓</strong></a>)}</div></section><section className="section section-tinted"><p className="section-label">For builders</p><h2>Learn one path at a time.</h2><div className="doc-reference-grid"><a href={sourcePath('marketing/tutorials/client-integration.md')}><span>Tutorial 01</span><h3>Connect one AI client</h3><p>Configuration, unique identity, compatibility boundaries, and a verification checklist.</p><strong>Read walkthrough ↗</strong></a><a href={sourcePath('marketing/tutorials/policy-and-evidence.md')}><span>Tutorial 02</span><h3>Preview policy and inspect evidence</h3><p>Begin offline. Understand the managed activation boundary before changing shared state.</p><strong>Read walkthrough ↗</strong></a></div></section><section className="section prose-section"><p className="section-label">An open-source project</p><h2>Help make the first run better.</h2><p>Start with <a href={sourcePath('CONTRIBUTING.md')}>contribution guidance</a>, join <a href={REPOSITORY + '/discussions/211'}>the onboarding discussion</a>, or choose a <a href={sourcePath('marketing/CONTRIBUTOR_STARTERS.md')}>bounded newcomer task</a>. Reports should use synthetic examples and omit credentials or customer content.</p><p><a href={sourcePath('docs/ROADMAP.md')}>The roadmap</a> separates shipped capability from open gates. v1.0.0 stabilizes source CLI, policy, and evidence contracts; independent human onboarding and production qualification remain separate work. Proposed v1.1 portfolio features are not advertised as shipped.</p><p>Maintained by <strong>Mehrdad Zaker</strong>. Hormuz is Apache-2.0. The project is not represented as selected, endorsed, or sponsored by OpenAI.</p></section></PageFrame>;
}
