'use client';

import { useState } from 'react';
import { evaluateExamplePolicy, policyTemplate } from '../../lib/customer-example.mjs';
import { sourcePath } from '../../lib/site.mjs';
import { CodeBlock } from './CodeBlock';
import { usd } from './SpendExample';

export function PolicyExample() {
  const [candidate, setCandidate] = useState(() => policyTemplate('strict'));
  const [active, setActive] = useState(() => policyTemplate('standard'));
  const [previous, setPrevious] = useState<ReturnType<typeof policyTemplate> | null>(null);
  const [nearLimit, setNearLimit] = useState(false);
  const [model, setModel] = useState('Advanced');
  const [secret, setSecret] = useState(false);
  const [message, setMessage] = useState('Standard is active in this example. A Strict candidate is ready to compare.');
  const current = evaluateExamplePolicy(active, { nearLimit, model, secret });
  const preview = evaluateExamplePolicy(candidate, { nearLimit, model, secret });
  const changed = JSON.stringify(candidate) !== JSON.stringify(active);
  function reset() { setCandidate(policyTemplate('strict')); setActive(policyTemplate('standard')); setPrevious(null); setNearLimit(false); setModel('Advanced'); setSecret(false); setMessage('Example reset. Historical usage stays unchanged.'); }
  return <div>
    <div className="experience-view-heading"><div><span className="experience-kicker">YOU ARE THE POLICY ADMINISTRATOR</span><h3>Choose a template. See what changes.</h3></div><button className="quiet-button" onClick={reset}>Reset example ↺</button></div>
    <p className="chapter-intro">Keep Engineering inside a $45,000 monthly ceiling. Start from a real template, compare the next request, then apply the candidate to this example.</p>
    <div className="policy-workspace">
      <div className="policy-editor"><div className="policy-scope"><span>Organization → Engineering</span><strong>Candidate policy</strong></div><fieldset className="template-picker"><legend>1. Start with a template</legend>{['standard', 'strict', 'lockdown'].map(name => <button type="button" key={name} onClick={() => setCandidate(policyTemplate(name))} aria-pressed={candidate.template === name}>{name[0].toUpperCase() + name.slice(1)}</button>)}</fieldset>
        <p className="field-explainer">{candidate.template === 'lockdown' ? 'Empty model and client allowlists · all requests denied.' : `${candidate.outputCap.toLocaleString('en-US')} output tokens · configured secrets ${candidate.secrets === 'redact' ? 'redacted' : 'denied'}.`} Templates inherit configured model/client lists; budgets are added explicitly.</p>
        <label className="example-field">2. Team monthly budget (USD)<input type="number" min="0" max="83333.33" step="0.01" value={Number.isNaN(candidate.budget) ? '' : candidate.budget} onChange={event => setCandidate({ ...candidate, budget: event.target.value === '' ? NaN : Number(event.target.value) })} /></label>
        <label className="example-field">3. Maximum output tokens <strong>{candidate.outputCap.toLocaleString('en-US')}</strong><input type="range" min="1000" max="16000" step="1000" value={candidate.outputCap} onChange={event => setCandidate({ ...candidate, outputCap: Number(event.target.value) })} /></label>
        <fieldset className="model-checks"><legend>4. Approved models</legend><label><input type="checkbox" checked={candidate.advanced} onChange={event => setCandidate({ ...candidate, advanced: event.target.checked, template: 'custom' })} /> Advanced</label><label><input type="checkbox" checked={candidate.standard} onChange={event => setCandidate({ ...candidate, standard: event.target.checked, template: 'custom' })} /> Standard</label></fieldset>
        <label className="example-field">5. Configured secret detection<select value={candidate.secrets} onChange={event => setCandidate({ ...candidate, secrets: event.target.value })}><option value="redact">Redact before forwarding</option><option value="deny">Deny the request</option></select></label>
        <fieldset className="model-checks"><legend>6. Client access</legend><label><input type="checkbox" checked={candidate.clientAllowed} onChange={event => setCandidate({ ...candidate, clientAllowed: event.target.checked, template: 'custom' })} /> Allow Codex for this team</label></fieldset>
      </div>
      <div className="policy-result"><span className="experience-kicker">COMPARE BEFORE APPLYING</span><h4>What happens to the next request?</h4><label className="example-field">Requested model<select aria-label="Requested model" value={model} onChange={event => setModel(event.target.value)}><option>Advanced</option><option>Standard</option></select></label><label className="check-line"><input type="checkbox" checked={nearLimit} onChange={event => setNearLimit(event.target.checked)} /> Try a near-limit month: $44,999.50 already occupied</label><label className="check-line"><input type="checkbox" checked={secret} onChange={event => setSecret(event.target.checked)} /> Include a detected test secret</label>
        <div className="policy-comparison">{[['Active', current, active], ['Candidate', preview, candidate]].map(([label, value, config]) => { const result = value as typeof current; const setting = config as typeof active; return <div key={label as string}><span>{label as string}</span><strong className={`decision-${result.decision}`}>{result.decision === 'invalid' ? 'Check values' : result.decision === 'allowed' ? 'Allowed' : 'Denied'}</strong><dl><div><dt>Output cap</dt><dd>{setting.outputCap.toLocaleString('en-US')}</dd></div><div><dt>Output charge ceiling</dt><dd>{usd(result.outputCeiling, true)}</dd></div><div><dt>Request reservation</dt><dd>{usd(result.reservation, true)}</dd></div><div><dt>Available before</dt><dd>{usd(result.available, true)}</dd></div><div><dt>Provider calls</dt><dd>{result.calls}</dd></div></dl><p>{result.reason}</p></div>; })}</div>
        <div className="policy-apply"><button className="experience-action" disabled={!changed || preview.decision === 'invalid'} onClick={() => { setPrevious(active); setActive({ ...candidate }); setMessage('Candidate applied to the example. New requests use this policy; historical usage and requests already in flight keep their original facts.'); }}>Apply to example →</button><button className="quiet-button" disabled={!previous} onClick={() => { if (previous) { setActive(previous); setPrevious(null); setMessage('Previous policy restored for new example requests. History stays intact.'); } }}>Undo change</button></div><p className="example-live" role="status">{message}</p>
      </div>
    </div>
    <p className="experience-footnote">At the invented Advanced rate, a 16,000 → 4,000 cap lowers the maximum output charge from $0.64 to $0.16. Input charges are separate. This is a ceiling, not measured savings. No provider calls or policy changes occur outside this teaching example.</p>
    <details className="experience-details"><summary>How do I do this in the actual product?</summary><p>A policy administrator uses the CLI and a validated policy document. The browser console preview does not grant policy authority. Standard, Strict, and Lockdown are real templates. This example’s team budget, model names, and form are illustrative.</p><CodeBlock label="Create and validate a real candidate locally" code={'hormuz policy templates\nhormuz --config hormuz.json policy create \\\n  --template strict --output candidate.json\nhormuz --config hormuz.json policy validate candidate.json'} /><p>Review the candidate against configured model/client aliases, add the intended team overlay, then compare and preview before a guarded activation. Templates do not create team scopes or budgets for you. <a href={sourcePath('docs/POLICY_CONTROL.md')}>Validated schema, compare, preview, apply, and rollback commands ↗</a></p></details>
    <details className="experience-details"><summary>Who can change what, and when does it take effect?</summary><p>Administrators set model/client access, fallback routes, output caps, organization/team/person token or USD budgets, and redaction/denial rules. Lower scopes can tighten ancestor policy but cannot loosen it. Atomic reservations protect against competing requests. A preview needs its stated usage and reservation inputs; incomplete evidence is not an approval.</p><p>Managed activation creates an immutable policy version. New requests read the active version; requests in flight keep their original snapshot. A guarded apply refuses a concurrent version change. Rollback creates a new activation and retains the history. A smaller model may behave differently: evaluate the work before changing access or routing.</p></details>
  </div>;
}
