import { commercial, PAYMENT_KEYS } from '../../lib/commercial.mjs';
import { pageMetadata } from '../../lib/metadata';
import { CONTACT_EMAIL, sitePath, sourcePath } from '../../lib/site.mjs';
import { PageFrame, PageHero } from '../components/PageFrame';
import { AdPreferencesButton } from '../components/AdConsent';

export const metadata = pageMetadata('Website privacy — Hormuz', 'How the public website handles workflow inquiries, optional measurement, booking, and payments, with a separate AI Work data-handling summary.', '/privacy/');

export default function PrivacyPage() {
  return <PageFrame active="privacy">
    <PageHero eyebrow="Website privacy" title={<>Your inquiry.<br /><span>Your choice to share.</span></>}>
      <p>Last updated October 8, 2026. This notice covers the static website. Your gateway operator supplies deployment-specific retention, access, and service terms; the AI Work summary below explains the implemented data boundary.</p>
    </PageHero>
    <section className="section prose-section">
      <h2>What happens when you visit</h2>
      <p>Fonts and the recorded demo are served with the site; no third-party video player is embedded. Optional Google Analytics and X Ads measurement each stay off until you allow that service using this website’s privacy choices. Safari and browsers on iPhone and iPad do not load X Ads code; you can choose website analytics independently.</p>
      <p>GitHub Pages hosts the site and receives the requested URL, including its path and query string, in the initial HTTP request. Campaign parameters in a URL therefore reach the host before this application reads them. Requested URLs may be processed in hosting/security logs.</p>
      <p>GitHub states that Pages logs visitor IP addresses for security, including visits by people who are not signed in. See <a href="https://docs.github.com/en/pages/getting-started-with-github-pages/what-is-github-pages">GitHub Pages documentation</a> and <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub’s privacy statement</a> for its processing. Declining ad measurement does not disable hosting logs.</p>
      {commercial.formEndpoint ? <>
        <h2>When you submit an application</h2>
        <p>The application sends your name, work email, organization, workflow, interest, a random request reference, and optional timing to Formspree for Hormuz to review and respond. Formspree processes the submission and may apply spam filtering. See <a href="https://formspree.io/legal/privacy-policy/">Formspree’s privacy policy</a>. This is an inquiry, not consent to a marketing email subscription.</p>
        <p>Your entries stay in temporary page state while you complete the form. This application does not store them in cookies or browser storage. The submission request identifies the website origin to Formspree for domain filtering; its referrer header excludes the page path and query parameters. A receipt message appears only after the service acknowledges the submission; it does not mean a meeting, payment, or service agreement is confirmed.</p>
        <p>To request access to or deletion of an inquiry, email <a href={'mailto:' + CONTACT_EMAIL}>{CONTACT_EMAIL}</a>. Do not submit credentials, prompts, customer data, or confidential configurations.</p>
      </> : <>
        <h2>You choose when to move a draft out of this page</h2>
        <p>The contact form uses temporary page state. It does not submit form entries, save them to a server or browser storage, or confirm email delivery. Preparing a draft creates a mailto link and a copyable message. When you choose Open email app or paste the draft into another service, that app or service may process or save it before you send. Its privacy settings and policies apply.</p>
      </>}
      <p>Internal page links retain only bounded utm_source, utm_medium, utm_campaign, and utm_content parameters from the current page URL. The application includes them with your inquiry only if you select the unchecked campaign-source checkbox. This choice is separate from optional Google Analytics and X Ads measurement and does not change the initial URL request already received by GitHub Pages. Do not put personal information or secrets in campaign URLs.</p>
      <h2 id="analytics">Optional website analytics</h2>
      <p>If you select Website analytics and save your choices, Google Analytics measures page visits, campaign labels, evidence and AI Work entry clicks, opened demo sections, install-link clicks, and sales inquiries acknowledged by Formspree. It receives the page route and referring site’s origin, browser and network information, and an analytics cookie identifier. Google Analytics cookies are configured to expire after 180 days without refreshing that expiry on each visit. We disable Google signals and advertising personalization for this stream.</p>
      <p>Analytics events do not include names, email addresses, organizations, workflow descriptions, request references, arbitrary URL parameters or fragments, or referrer paths. Explicit QA pages and local previews do not report to production. An install-link click does not confirm installation, and an inquiry does not confirm a booking, qualified buyer, or payment. See <a href="https://policies.google.com/privacy">Google’s privacy policy</a> for Google’s processing.</p>
      <p>Website analytics has its own consent choice. An earlier choice to allow X does not allow Google Analytics. We remember each preference for up to 180 days and honor Global Privacy Control and Do Not Track by keeping optional measurement off.</p>
      <h2 id="advertising">Optional X Ads measurement</h2>
      <p>In supported browsers, if you select X ad measurement and save your choices, the X Pixel measures site visits and sales inquiries, including engineering workflow inquiries, acknowledged by Formspree. Safari and browsers on iPhone and iPad keep X measurement off for site reliability. X may use browser and network information, cookies, and an X ad click identifier to associate activity with ads and improve advertising. General integration, security, and community inquiries, marked QA tests, and filled spam traps do not trigger this sales event. An acknowledged inquiry is not a qualified buyer or a sale. An application event contains no name, email address, organization, workflow text, payment amount, or other form entry. We enable X’s page-location suppression and do not create website activity audiences for this event.</p>
      <p>We remember your allow or decline choice in browser storage for up to 180 days, without a visitor identifier. If storage is unavailable, the choice lasts only for the current page. We respect Global Privacy Control and Do Not Track signals by keeping measurement off. Declining does not prevent submitting an inquiry, booking, or paying.</p>
      <p>You can change your choices below or using Privacy choices in any page footer. Turning off an active service reloads the page to unload it; copy unfinished form entries first. It stops future measurement on this website but does not remove data already sent to Google or X. Cookies already set may remain until they expire or you clear them in your browser.</p>
      <AdPreferencesButton />
      <p>For X’s data practices, cookie lifetimes, and broader advertising opt-outs, see <a href="https://x.com/en/privacy">X’s privacy policy</a>, <a href="https://help.x.com/en/rules-and-policies/x-cookies">X’s cookie policy</a>, and <a href="https://help.x.com/en/safety-and-security/privacy-controls-for-tailored-ads">X’s personalized-ad privacy controls</a>.</p>
      {(commercial.bookingUrl || PAYMENT_KEYS.some(key => commercial[key])) && <><h2>Booking and payment services</h2><p>Booking and payment links open external services only when you choose them. Those services receive the details you enter and apply their own privacy policies and terms. Hormuz’s static website does not collect card details or confirm payment from a return URL. Review the named merchant, amount, billing interval, and cancellation terms before paying.</p></>}
      <h2>Workflow discussion bookings</h2><p>Google Calendar manages the discussion schedule, checks the organizer’s calendar for conflicts, and sends invitation and reminder emails. It collects your name, email, and any optional organization or request reference you supply. It requires email verification for visitors who are not signed in to Google. Booking details stay with Google and the organizer; this site does not report bookings as confirmed X Ads conversions.</p><h2>After you choose to email</h2>
      <p>Your email may contain contact details and a workflow description. Send only information needed for the conversation. Do not include credentials, prompts, customer data, or other secrets. Ask Mehrdad Zaker at <a href={'mailto:' + CONTACT_EMAIL}>{CONTACT_EMAIL}</a> about deleting an inquiry or changing contact preferences.</p>
      <h2>Interactive examples</h2><p>The priority explanation, company report, policy editor, compaction inspector, setup selector, and question search use fictional or synthetic data and temporary state in your browser. They do not connect to a gateway, read your local AI usage, or apply policies. If you allow website analytics, selecting a demo section records its fixed name (spend, policy, compaction, or setup). Example values, policy settings, and search text are not included. A download or checkout link click is not proof of installation, activation, payment, or delivery of paid services.</p>
      <h2 id="ai-work-data">AI Work gateway data</h2><p>The public AI Work entry links to a configured trusted gateway. It collects no gateway tokens, provider keys, task descriptions, or repository contents. Authentication and private work records belong to that gateway.</p><p>The opt-in AI Work runtime persists bounded work metadata in SQLite: ownership, repository and task labels, caller-supplied context revision and optional job title, budgets, attempts, costs, timing, and submitted observation references. A supplied title is a label, not automatic prompt capture. Prompts, response bodies, patches, and tool output are not written to this work ledger. Keep sensitive material out of display labels and references.</p><p>Exact answer reuse is separately opt-in and Off by default. When enabled, eligible response bodies remain in bounded gateway process memory with an explicit expiry; restart clears them. Cache bodies and prompts are not persisted to SQLite. Work, identity, context, model, policy, and request validity constrain reuse, and correction can invalidate it. Your operator is responsible for metadata retention, backups, access, infrastructure logging, and provider processing terms.</p><p><a href={sourcePath('docs/AI_WORK_RUNTIME.md')}>Read the complete runtime and cache contract ↗</a> · <a href={sitePath('/security/#data-handling')}>Review the gateway data path →</a></p>
      <h2>External destinations</h2>
      <p>GitHub source, release, and community links leave this website. Their services apply their own terms. Downloading a synthetic demo or opening a link is not counted as a verified user, customer, or successful evaluation.</p>
    </section>
  </PageFrame>;
}
