"""Client versions qualified for the Hormuz launcher contract."""

SUPPORTED_CODEX_VERSION = "0.147.0"
SUPPORTED_CLAUDE_CODE_VERSION = "2.1.233"
SUPPORTED_AIDER_VERSION = "0.86.2"

SUPPORTED_CLIENT_VERSIONS = {
    "codex": SUPPORTED_CODEX_VERSION,
    "claude-code": SUPPORTED_CLAUDE_CODE_VERSION,
    "aider": SUPPORTED_AIDER_VERSION,
}
