import { pageMetadata } from '../../lib/metadata';
import { PageFrame, PageHero } from '../components/PageFrame';
import { CampaignLink } from '../components/CampaignLink';
import { DemoPlayer } from '../components/DemoPlayer';
import { AiWorkDemo } from '../components/AiWorkDemo';
import { REPOSITORY, sitePath, sourcePath } from '../../lib/site.mjs';
import gateway from '../../public/demo/gateway.json';
import proof from '../../public/downloads/ai-work-proof.json';

const workChecks = [
  ['local_cost_evidence_selects_lower_observed_cost', 'Select a route from local cost observations'],
  ['exact_cache_hit_skips_provider', 'Exact reuse skips another provider call'],
  ['cache_hit_does_not_claim_completed_work', 'A cache hit leaves work completion separate'],
  ['correction_bypasses_cached_answer', 'Correction bypasses the cached answer'],
  ['job_cap_stops_before_provider_egress', 'A job cap stops dispatch before provider egress'],
  ['explicit_allowance_continues_same_job', 'Explicit allowance continues the same work'],
  ['fallback_attempts_join_same_job', 'Fallback attempts stay attributed to their work'],
  ['uncertain_provider_charge_retains_hold', 'Missing usage preserves an uncertain hold'],
  ['openai_compatible_chat_is_accounted', 'Chat Completions attempts enter work accounting'],
  ['missing_authentication_cannot_read_work', 'An unauthenticated request cannot read work'],
];

export const metadata = pageMetadata('Evidence — Hormuz', 'Inspect recorded provider-free gateway mechanics, transcripts, provenance, and the boundary between functional evidence and customer performance results.', '/evidence/');

export default function EvidencePage() {
  const passed = proof.checks.filter(check => check.passed).length;
  return <PageFrame active="evidence"><PageHero eyebrow="Inspect the execution" title={<>Working controls.<br /><em>Inspectable evidence.</em></>}><p>See actual local executions of work accounting, budget enforcement, route selection, and exact reuse. Inspect the conditions before connecting your own workflow.</p><div className="hero-actions"><a className="button landing-primary" href="#work-demo">See AI Work in action ↓</a><CampaignLink className="button landing-secondary" href={sitePath('/contact/?interest=work')}>Discuss your workflow →</CampaignLink></div></PageHero>
    <AiWorkDemo />
    <section className="section prose-section" id="work-proof"><h2>AI Work mechanics, actually executed.</h2><p>This receipt comes from the real gateway, SDK, and runtime against a synthetic provider fixture on loopback. The execution passed {passed} of {proof.checks.length} checks across {proof.provider_fixture_calls} local fixture calls, with {proof.conditions.real_provider_calls} real-provider calls and {proof.conditions.real_payments} payments.</p><p>Configured costs are synthetic estimates. Request timings measure this local fixture execution. These amounts and timings establish no paid-provider saving, customer speed improvement, or production model quality.</p><div className="table-scroll"><table className="comparison-table work-proof-checks"><caption>Selected checks in the synthetic fixture</caption><thead><tr><th scope="col">Mechanic</th><th scope="col">Observed check</th></tr></thead><tbody>{workChecks.map(([name, label]) => <tr key={name}><th scope="row">{label}</th><td>{proof.checks.find(check => check.check === name)?.passed ? 'Passed' : 'Not established'}</td></tr>)}</tbody></table></div><div className="resource-actions"><CampaignLink className="button landing-primary" href={sitePath('/downloads/ai-work-proof.json')} download>Download the complete work receipt ↓</CampaignLink><a className="text-link" href={sourcePath('tools/ai_work_proof.py')}>Read the reproducible execution script ↗</a></div><details className="disclosure"><summary>Execution conditions and source provenance</summary><p>Generated {proof.generated_at}. The receipt identifies working-tree source files by SHA-256, from base revision <a href={`${REPOSITORY}/tree/${proof.source_commit}`}>{proof.source_commit.slice(0,12)} ↗</a>. The base revision alone is not the executed implementation.</p><p>The fixture uses a minimum sample count of {proof.conditions.minimum_samples} to exercise selection mechanics. This does not establish statistical confidence or a production quality threshold. Observations come from declared executed fixture checks and corrections.</p><p>The download includes the request trace and synthetic metadata-only work records. It contains no actual customer result, provider invoice, payment, or validated savings claim.</p></details></section>
    <section className="section" id="recording"><div className="section-heading narrow"><h2>The governed request path.</h2><p>This recording executes the real CLI and gateway against a loopback provider simulator: allow, fallback and cap, redact, and deny. It makes zero external provider calls.</p></div><DemoPlayer recording={gateway} /><details className="disclosure"><summary>Read the complete unmodified transcript</summary><pre tabIndex={0}><code>{gateway.transcript}</code></pre></details><p className="after-grid">Recorded {gateway.recorded_at.slice(0,10)}, exit code {gateway.exit_code}, Python {gateway.python}, source revision <a href={`${REPOSITORY}/tree/${gateway.source_revision}`}>{gateway.source_revision.slice(0,12)} ↗</a>.</p><div className="resource-actions"><CampaignLink className="text-link" href={sitePath('/demo/gateway.json')} download>Recording and provenance ↓</CampaignLink><CampaignLink className="text-link" href={sitePath('/demo/gateway.txt')} download>Plain-text transcript ↓</CampaignLink><CampaignLink className="text-link" href={sitePath('/demo/synthetic-evidence.jsonl')} download>Synthetic metadata export ↓</CampaignLink></div></section>
    <section className="section prose-section" id="qualification"><h2>Mechanics proof and customer value are different evidence.</h2><div className="table-scroll"><table className="comparison-table"><caption>How to read this evidence</caption><thead><tr><th>Evidence</th><th>What it establishes</th><th>What still requires qualification</th></tr></thead><tbody><tr><th scope="row">Provider-free execution</th><td>Actual request controls and recorded gateway behavior under declared synthetic conditions.</td><td>Live-provider compatibility, reliability at customer load, and actual billed cost.</td></tr><tr><th scope="row">Local work observations</th><td>Attempts, captured usage, elapsed time, and available completion or correction events.</td><td>Comparable workload coverage and enough observations to choose an alternative confidently.</td></tr><tr><th scope="row">Customer cost or speed comparison</th><td>A whole-work comparison when collected with declared conditions, overhead, and unresolved outcomes.</td><td>No customer performance result or guaranteed savings is claimed on this page.</td></tr></tbody></table></div><p>Passing checks credits only their stated outcome. No corrective follow-up is an absence of observed rework, not proof of correctness. High cache reuse does not establish completion.</p><div className="resource-actions"><CampaignLink className="text-link" href={sitePath('/demo/#recording')}>More recorded policy evidence →</CampaignLink><CampaignLink className="text-link" href={sitePath('/integrations/')}>Check your exact stack →</CampaignLink><CampaignLink className="text-link" href={sitePath('/work/')}>Open AI Work →</CampaignLink></div></section>
  </PageFrame>;
}
