import Foundation

public struct ConnectorFile: Sendable {
    public let name: String
    public let content: Data
    public let previous: Data?
    public let executable: Bool
}

/// Dedicated launchers apply overrides for that invocation only. They do not
/// read or edit ~/.codex/config.toml, ~/.claude/settings.json, or auth files.
public struct ConnectorPlan: Sendable {
    public let profile: ConnectionProfile
    public let files: [ConnectorFile]
    public let launcher: URL
    public var command: String { Self.shellQuote(launcher.path) }

    /// Bind this invocation only. The authenticated gateway verifies access to
    /// the job; the identifier is never saved in the profile or launcher file.
    public func command(workID: String) throws -> String {
        let bytes = Array(workID.utf8)
        let alphanumeric: (UInt8) -> Bool = { (48...57).contains($0) || (65...90).contains($0) || (97...122).contains($0) }
        guard (1...128).contains(bytes.count), let first = bytes.first, alphanumeric(first),
              bytes.allSatisfy({ alphanumeric($0) || [46, 95, 45].contains($0) })
        else { throw ClientError.invalidArguments }
        return command + " --work-id " + Self.shellQuote(workID)
    }

    public static func preview(
        profile: ConnectionProfile,
        directory: PrivateDirectory,
        helper: URL,
        contextHelper suppliedContextHelper: URL? = nil,
        relay suppliedRelay: URL? = nil,
        ownerSocket: URL
    ) throws -> ConnectorPlan {
        let profile = try profile.validated()
        guard helper.isFileURL, helper.path.hasPrefix("/"),
              !helper.path.unicodeScalars.contains(where: { CharacterSet.controlCharacters.contains($0) }) else {
            throw ClientError.invalidArguments
        }
        let contextHelper = suppliedContextHelper ?? helper.deletingLastPathComponent()
            .deletingLastPathComponent()
            .appendingPathComponent("Resources/ContextHelper/hormuz-context")
        guard contextHelper.isFileURL, contextHelper.path.hasPrefix("/"),
              !contextHelper.path.unicodeScalars.contains(where: { CharacterSet.controlCharacters.contains($0) })
        else { throw ClientError.invalidArguments }
        let relay = suppliedRelay ?? helper.deletingLastPathComponent()
            .deletingLastPathComponent().appendingPathComponent("Helpers/hormuz-client-relay")
        for path in [relay, ownerSocket] {
            guard path.isFileURL, path.path.hasPrefix("/"),
                  !path.path.unicodeScalars.contains(where: { CharacterSet.controlCharacters.contains($0) })
            else { throw ClientError.invalidArguments }
        }
        let stem = profile.client.rawValue + "-" + profile.key
        var outputs: [(String, Data, Bool)] = []
        let header = "#!/bin/sh\n# Generated by Hormuz. No credentials are stored here.\nset -eu\n"
        let arguments = [relay.path, "--profile", profile.key,
                         "--state-directory", directory.root.path, "--credential-helper", helper.path,
                         "--optimizer-helper", contextHelper.path]
        // The relay owns both On and Off launches, snapshots the preference
        // per request, and gives the client only a fresh loopback credential.
        // Only a bounded optional job ID is accepted. Arbitrary flags cannot
        // replace the governed endpoint, model, custody helper or owner lease.
        let script = header
            + "if [ \"$#\" -ne 0 ]; then\n"
            + "  if [ \"$#\" -ne 2 ] || [ \"$1\" != '--work-id' ]; then echo 'Use no arguments or --work-id <job-id>.' >&2; exit 2; fi\n"
            + "  if ! (LC_ALL=C; export LC_ALL; case \"$2\" in ''|[!A-Za-z0-9]*|*[!A-Za-z0-9._-]*) exit 1 ;; esac; [ \"${#2}\" -le 128 ]); then echo 'Invalid Hormuz job ID.' >&2; exit 2; fi\n"
            + "fi\n"
            + "unset OPENAI_API_KEY OPENAI_BASE_URL OPENAI_ORGANIZATION OPENAI_PROJECT CODEX_API_KEY\n"
            + "unset ANTHROPIC_API_KEY ANTHROPIC_AUTH_TOKEN CLAUDE_CODE_OAUTH_TOKEN ANTHROPIC_CUSTOM_HEADERS\n"
            + "unset CLAUDE_CODE_USE_BEDROCK CLAUDE_CODE_USE_VERTEX CLAUDE_CODE_USE_FOUNDRY\n"
            + "exec " + arguments.map(shellQuote).joined(separator: " ") + " \"$@\""
            + " '--owner-socket' " + shellQuote(ownerSocket.path) + "\n"
        let launcherName = stem + ".command"
        outputs.append((launcherName, Data(script.utf8), true))
        let files = try outputs.map { ConnectorFile(name: $0.0, content: $0.1, previous: try directory.read($0.0), executable: $0.2) }
        return ConnectorPlan(profile: profile, files: files, launcher: try directory.fileURL(launcherName))
    }

    public func apply(in directory: PrivateDirectory) async throws {
        let lock = try await directory.lock()
        defer { lock.unlock() }
        try directory.requireSetupWritable()
        guard try directory.loadProfile() == profile else { throw ClientError.configurationChanged }
        // Check every snapshot before touching any file. A partially completed
        // write can be retried from a fresh preview without rewriting user files.
        for file in files {
            guard try directory.read(file.name) == file.previous else { throw ClientError.configurationChanged }
        }
        for file in files where file.content != file.previous {
            // Preserve modifications to Hormuz-owned files as well.
            if let previous = file.previous {
                let previousScript = Self.withoutOwnerLease(previous)
                if previousScript == nil || previousScript != Self.withoutOwnerLease(file.content) {
                    let backup = "backup-" + UUID().uuidString.lowercased() + ".txt"
                    try directory.write(previous, to: backup, expected: nil)
                }
            }
            try directory.write(file.content, to: file.name, expected: file.previous, executable: file.executable)
        }
        try NativeOwnership.record(files.map {
            NativeOwnedFile(name: $0.name, digest: NativeOwnership.digest($0.content), profileID: profile.id, kind: "launcher")
        }, directory: directory)
    }

    public var previewText: String {
        files.map { "# " + $0.name + "\n" + (String(data: $0.content, encoding: .utf8) ?? "") }.joined(separator: "\n\n")
    }

    private static func withoutOwnerLease(_ content: Data) -> Data? {
        // Only an otherwise byte-identical generated launcher may replace its
        // per-app UUID lease without a backup. Preserve every other edit.
        let lease = " '--owner-socket' '/private/tmp/hormuz-owner-[0-9A-Fa-f]{8}"
            + "(?:-[0-9A-Fa-f]{4}){3}-[0-9A-Fa-f]{12}/lease'\\n$"
        guard let script = String(data: content, encoding: .utf8),
              let range = script.range(of: lease, options: .regularExpression),
              range.upperBound == script.endIndex else { return nil }
        return Data(script[..<range.lowerBound].utf8)
    }

    public static func shellQuote(_ value: String) -> String { "'" + value.replacingOccurrences(of: "'", with: "'\"'\"'") + "'" }
}
