import Foundation

public struct ConnectorFile: Sendable {
    public let name: String
    public let content: Data
    public let previous: Data?
    public let executable: Bool
}

/// Dedicated launchers apply overrides for that invocation only. They do not
/// read or edit ~/.codex/config.toml, ~/.claude/settings.json, or auth files.
public struct ConnectorPlan: Sendable {
    public let profile: ConnectionProfile
    public let files: [ConnectorFile]
    public let launcher: URL
    public var command: String { Self.shellQuote(launcher.path) }

    public static func preview(
        profile: ConnectionProfile,
        directory: PrivateDirectory,
        helper: URL,
        contextHelper suppliedContextHelper: URL? = nil
    ) throws -> ConnectorPlan {
        let profile = try profile.validated()
        guard helper.isFileURL, helper.path.hasPrefix("/"),
              !helper.path.unicodeScalars.contains(where: { CharacterSet.controlCharacters.contains($0) }) else {
            throw ClientError.invalidArguments
        }
        let contextHelper = suppliedContextHelper ?? helper.deletingLastPathComponent()
            .deletingLastPathComponent()
            .appendingPathComponent("Resources/ContextHelper/hormuz-context")
        guard contextHelper.isFileURL, contextHelper.path.hasPrefix("/"),
              !contextHelper.path.unicodeScalars.contains(where: { CharacterSet.controlCharacters.contains($0) })
        else { throw ClientError.invalidArguments }
        let stem = profile.client.rawValue + "-" + profile.key
        var outputs: [(String, Data, Bool)] = []
        let header = "#!/bin/sh\n# Generated by Hormuz. No credentials are stored here.\nset -eu\n"
        let arguments = [contextHelper.path, "context", "run", "--profile", profile.key,
                         "--state-directory", directory.root.path, "--credential-helper", helper.path]
        // The helper owns both On and Off launches, snapshots the preference
        // per request, and gives the client only a fresh loopback credential.
        // Do not accept flags that could replace the governed endpoint or model.
        let script = header
            + "if [ \"$#\" -ne 0 ]; then echo 'Open the Hormuz launcher without arguments.' >&2; exit 2; fi\n"
            + "unset OPENAI_API_KEY OPENAI_BASE_URL OPENAI_ORGANIZATION OPENAI_PROJECT CODEX_API_KEY\n"
            + "unset ANTHROPIC_API_KEY ANTHROPIC_AUTH_TOKEN CLAUDE_CODE_OAUTH_TOKEN ANTHROPIC_CUSTOM_HEADERS\n"
            + "unset CLAUDE_CODE_USE_BEDROCK CLAUDE_CODE_USE_VERTEX CLAUDE_CODE_USE_FOUNDRY\n"
            + "exec " + arguments.map(shellQuote).joined(separator: " ") + "\n"
        let launcherName = stem + ".command"
        outputs.append((launcherName, Data(script.utf8), true))
        let files = try outputs.map { ConnectorFile(name: $0.0, content: $0.1, previous: try directory.read($0.0), executable: $0.2) }
        return ConnectorPlan(profile: profile, files: files, launcher: try directory.fileURL(launcherName))
    }

    public func apply(in directory: PrivateDirectory) async throws {
        let lock = try await directory.lock()
        defer { lock.unlock() }
        guard try directory.loadProfile() == profile else { throw ClientError.configurationChanged }
        // Check every snapshot before touching any file. A partially completed
        // write can be retried from a fresh preview without rewriting user files.
        for file in files {
            guard try directory.read(file.name) == file.previous else { throw ClientError.configurationChanged }
        }
        for file in files where file.content != file.previous {
            // Preserve modifications to Hormuz-owned files as well.
            if let previous = file.previous {
                let backup = "backup-" + UUID().uuidString.lowercased() + ".txt"
                try directory.write(previous, to: backup, expected: nil)
            }
            try directory.write(file.content, to: file.name, expected: file.previous, executable: file.executable)
        }
    }

    public var previewText: String {
        files.map { "# " + $0.name + "\n" + (String(data: $0.content, encoding: .utf8) ?? "") }.joined(separator: "\n\n")
    }

    public static func shellQuote(_ value: String) -> String { "'" + value.replacingOccurrences(of: "'", with: "'\"'\"'") + "'" }
}
