import { pageMetadata } from '../../lib/metadata';
import { REPOSITORY, sitePath, sourcePath } from '../../lib/site.mjs';
import { PageFrame, PageHero } from '../components/PageFrame';
import { DemoPlayer } from '../components/DemoPlayer';
import { CodeBlock } from '../components/CodeBlock';
import gateway from '../../public/demo/gateway.json';
import policy from '../../public/demo/policy.json';

export const metadata = pageMetadata('Recorded demo & synthetic evidence — Hormuz', 'Watch a real provider-free Hormuz run, inspect the transcript and synthetic metadata, then reproduce it locally.', '/demo/');

export default function DemoPage() {
  return <PageFrame active="demo"><PageHero eyebrow="A real run. Synthetic inputs." title={<>See policy act.<br /><span>Then inspect the evidence.</span></>}><p>Recorded from the actual CLI against disposable loopback providers. No customer data, provider account, or simulated customer testimonial. Reproduce the same tour on your machine.</p><div className="hero-actions"><a className="button button-primary" href="#recording">Watch the recording ↓</a><a className="button button-ghost" href={sitePath('/docs/#quickstart')}>Run it yourself →</a></div></PageHero>
    <section id="recording" className="section"><div className="section-heading narrow"><p className="section-label">The gateway tour</p><h2>Allow. Reroute. Redact. Deny.</h2><p>The six PASS lines come from an actual execution. The recording is intentionally short; pause it, scrub it, or show the full output.</p></div><DemoPlayer recording={gateway} /><details className="disclosure"><summary>Read the complete gateway transcript</summary><pre tabIndex={0}><code>{gateway.transcript}</code></pre></details><p className="after-grid">Recorded {gateway.recorded_at.slice(0, 10)} with Python {gateway.python}, exit code {gateway.exit_code}, source revision <a href={`${REPOSITORY}/tree/${gateway.source_revision}`}>{gateway.source_revision.slice(0, 12)} ↗</a>. The product module was unchanged from that revision.</p><div className="resource-actions"><a className="text-link" href={sitePath('/demo/gateway.cast')} download>Download asciicast</a><a className="text-link" href={sitePath('/demo/gateway.txt')} download>Plain-text transcript</a><a className="text-link" href={sitePath('/demo/gateway.json')} download>Recording & provenance</a></div></section>
    <section className="section section-tinted"><div className="section-heading narrow"><p className="section-label">The administration tour</p><h2>Inspect a change before applying it.</h2><p>This separate zero-network run compares a baseline and stricter candidate, evaluates two scenarios, and makes no managed policy mutations.</p></div><CodeBlock code="hormuz policy demo" label="Reproduce the policy tour" /><details className="disclosure"><summary>Read the real policy-demo transcript</summary><pre tabIndex={0}><code>{policy.transcript}</code></pre></details><div className="resource-actions"><a className="text-link" href={sitePath('/demo/policy.cast')} download>Download policy asciicast</a><a className="text-link" href={sourcePath('marketing/tutorials/policy-and-evidence.md')}>Follow the policy walkthrough ↗</a></div></section>
    <section id="evidence" className="section prose-section"><p className="section-label">Synthetic evidence pack</p><h2>Five events. No conversation archive.</h2><p>Download four usage events and one secret-control event exported from a separate provider-free run. The gateway’s schema checks and forbidden-content checks passed before export. The records contain synthetic identities, model and policy outcomes, token/cost metadata, and bounded secret-control results—not prompt or response bodies.</p><div className="resource-actions"><a className="button button-primary" href={sitePath('/demo/synthetic-evidence.jsonl')} download>Download synthetic JSONL ↓</a><a className="text-link" href={sourcePath('docs/AUDIT.md')}>Read the audit contract ↗</a></div><p>This sample is not a customer case study, independent security review, invoice-reconciliation result, or performance test. These recorded executions do not count as independent people in the <a href={REPOSITORY + '/issues/110'}>external onboarding study</a>. That study has its own exact-archive protocol.</p></section>
  </PageFrame>;
}
